[project]
name = "parallel-coordinate-plot"
version = "0.1.0"
description = "A Python package for producing parallel coordinate plots."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
